// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveIdentityProviderID() {
  return window['go']['app']['App']['ActiveIdentityProviderID']();
}

export function CloudProviders() {
  return window['go']['app']['App']['CloudProviders']();
}

export function Connect(cloudProviderID) {
  return window['go']['app']['App']['Connect'](cloudProviderID);
}

export function IdentityProviders() {
  return window['go']['app']['App']['IdentityProviders']();
}

export function IsAuthenticated() {
  return window['go']['app']['App']['IsAuthenticated']();
}

export function ListInstances(cloudProviderID, accountID) {
  return window['go']['app']['App']['ListInstances'](cloudProviderID, accountID);
}

export function Login() {
  return window['go']['app']['App']['Login']();
}

export function LoginWith(identityProviderID) {
  return window['go']['app']['App']['LoginWith'](identityProviderID);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function ProviderUsable(cloudProviderID) {
  return window['go']['app']['App']['ProviderUsable'](cloudProviderID);
}
