// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ActiveIdentityProviderID():Promise<string>;

export function CloudProviders():Promise<Array<string>>;

export function Connect(cloudProviderID:string):Promise<void>;

export function IdentityProviders():Promise<Array<string>>;

export function IsAuthenticated():Promise<boolean>;

export function ListInstances(cloudProviderID:string,accountID:string):Promise<Array<app.VMData>>;

export function Login():Promise<void>;

export function LoginWith(identityProviderID:string):Promise<void>;

export function Logout():Promise<void>;

export function ProviderUsable(cloudProviderID:string):Promise<boolean>;
