// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActiveIdentity():Promise<string>;

export function ConnectProvider(arg1:string):Promise<void>;

export function IdentityProviders():Promise<Array<string>>;

export function IsAuthenticated():Promise<boolean>;

export function ListInstances(arg1:string,arg2:string):Promise<Array<main.VMData>>;

export function Login():Promise<void>;

export function LoginWith(arg1:string):Promise<void>;

export function Logout():Promise<void>;

export function Providers():Promise<Array<string>>;
