// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveIdentity() {
  return window['go']['main']['App']['ActiveIdentity']();
}

export function ConnectProvider(arg1) {
  return window['go']['main']['App']['ConnectProvider'](arg1);
}

export function IdentityProviders() {
  return window['go']['main']['App']['IdentityProviders']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function ListInstances(arg1, arg2) {
  return window['go']['main']['App']['ListInstances'](arg1, arg2);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function LoginWith(arg1) {
  return window['go']['main']['App']['LoginWith'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Providers() {
  return window['go']['main']['App']['Providers']();
}
